language: dart

dart:
- dev

addons:
  chrome: stable

script:
# Look for misconfigured dependencies
- ./tools/pub_get.sh --no-precompile

# Run tests
- ./tools/test.sh

# Build examples
- ./tools/build_examples.sh
