name: flur
description: Compiles Flutter apps to Javascript apps.
version: 0.0.1
authors:
- jban332 <jban332@gmail.com>
homepage: https://github.com/jban332/flur

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  flutter:
    git: git://github.com/jban332/flur_modified_flutter.git
  meta: '^1.1.1'

dev_dependencies:
  test: ^0.12.0