name: hello_world_browser

environment:
  sdk: ^2.0.0

dependencies:
  hello_world:
    path: ../hello_world
  flutter2js: any

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
  flutter_test: any
  test: ^1.3.0
  webdev: ^1.0.0

dependency_overrides:
  flutter2js:
    path: ../../packages/flutter2js
  flutter:
    path: ../../packages/flutter
  flutter_test:
    path: ../../packages/flutter_test