name: hello_world

environment:
  sdk: ^2.0.0

dependencies:
  flutter:
    path: ../../packages/flutter

dev_dependencies:
  flutter_test:
    path: ../../packages/flutter_test

flutter:
  uses-material-design: true
