name: flur
description: Compiles Flutter apps to Javascript apps.
version: 0.0.2

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  flutter:
    path: '../flutter'
  material_design_icons: any
  meta: '^1.1.1'

dev_dependencies:
  test: ^0.12.0