name: flutter2js
description: Compiles Flutter apps to Javascript apps.
version: 0.2.0

executables:
  flutter2js: flutter2js

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  args: '^1.2.0'
  flutter:
    path: ../flutter
  meta: ^1.1.6

dev_dependencies:
  test: '^1.3.0'
