name: stocks_browser

environment:
  sdk: ^2.0.0

dependencies:
  stocks:
    path: ../stocks
  flutter2js:
    path: ../../packages/flutter2js
  flutter:
    path: ../../packages/flutter
  flutter_localizations:
    path: ../../packages/flutter_localizations
  flutter_test:
    path: ../../packages/flutter_test

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
  webdev: ^1.0.0
