name: todo_browser
description: An example application (browser version)
version: 0.0.1

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  flur: any
  flur_react: any
  flutter:
    git:
      url: "git://github.com/jban332/flur.git"
      path: "packages/flutter"

dependency_overrides:
  flur:
    path: "../../packages/flur"
  flur_react:
    path: "../../packages/flur_react"
  flutter:
    path: "../../packages/flutter"

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- dart_to_js_script_rewriter
- $dart2js:
    checked: true