name: stocks
dependencies:
  flutter: any
  intl: '>=0.14.0 <0.16.0'
  intl_translation: '>=0.14.0 <0.16.0'
  http: '>=0.11.3+12'
  isolate: '>=1.0.0'

dependency_overrides:
  flutter:
    path: "../../packages/flutter"

flutter:
  uses-material-design: true
