name: stocks
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: '^0.15.2'
  intl_translation: '^0.16.1'
  http: '^0.11.3+14'
  isolate: '^1.1.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true