name: stocks

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    path: ../../packages/flutter
  flutter_localizations:
    path: ../../packages/flutter_localizations
  intl: ^0.15.7
  intl_translation: ^0.17.1
  http: ^0.12.0
  isolate: ^2.0.2

dev_dependencies:
  flutter_test:
    path: ../../packages/flutter_test

flutter:
  uses-material-design: true
