name: flutter_test

environment:
  sdk: ^2.0.0

dependencies:
  flutter:
    path: ../flutter

  # We depend on very specific internal implementation details of the
  # 'test' package, which change between versions, so when upgrading
  # this, make sure the tests are still running correctly.
  test: 1.3.0

  # Used by golden file comparator
  path: ^1.6.2

  # We use FakeAsync and other testing utilities.
  quiver: ^2.0.0+1

  # We import stack_trace because the test packages uses it and we
  # need to be able to unmangle the stack traces that it passed to
  # stack_trace. See https://github.com/dart-lang/test/issues/590
  stack_trace: ^1.9.3

  # Used by globalToLocal et al.
  vector_math: ^2.0.8